[java]
disabled = true

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context (\($namespace\))](dimmed green) '
style = "green"
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 8
